---
- hosts: localhost
  tasks:
    - name: remove known host
      known_hosts:
        name: k8s.fcd.dev
        state: absent
      tags: redo

- hosts: k8s.fcd.dev

  tasks:
    - name: Download kubeadm, kubectl, kubelet
      get_url:
        url: https://storage.googleapis.com/kubernetes-release/release/v1.19.0/bin/linux/amd64/{{ binary }}
        dest: /usr/local/bin
        mode: 0755
      loop_control:
        loop_var: binary
      loop:
        - kubeadm
        - kubectl
        - kubelet
      become: yes

    - name: docker key
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
      become: yes

    - name: docker repo
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/debian buster stable
      become: yes

    - name: docker install
      package:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
      become: yes

    - name: docker config
      copy:
        src: docker-daemon.json
        dest: /etc/docker/daemon.json
      notify: docker-restart
      become: yes

    - meta: flush_handlers

    - name: apt upgrade
      apt:
        upgrade: yes
        update_cache: yes
      become: yes
      when: ansible_os_family == "Debian"

    - name: reqs
      package:
        name:
          - conntrack
          - ethtool
          - fish
          - socat
          - tmux
          - vim
      become: yes

    - name: kubelet service
      copy:
        src: kubelet.service
        dest: /etc/systemd/system/kubelet.service
      become: yes

    - name: kubelet drop-in dir
      file:
        path: /etc/systemd/system/kubelet.service.d/
        state: directory
      become: yes

    - name: kubelet drop-in
      copy:
        src: kubeadm.conf
        dest: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
      become: yes

    - name: enable kubelet
      systemd:
        daemon_reload: true
        name: kubelet
        enabled: true
      become: yes

    - name: user bin
      file:
        path: '{{ ansible_user_dir }}/bin'
        state: directory

    - name: chezmoi
      unarchive:
        src: https://github.com/twpayne/chezmoi/releases/download/v1.8.5/chezmoi_1.8.5_linux_amd64.tar.gz
        dest: '{{ ansible_user_dir }}/bin'
        mode: 0755
        remote_src: true

    - name: chezmoi init
      command: '{{ ansible_user_dir }}/bin/chezmoi init https://gitlab.com/femnad/chezmoi.git'

    - name: chezmoi pull
      git:
        repo: https://gitlab.com/femnad/chezmoi.git
        dest: '{{ ansible_user_dir }}/.local/share/chezmoi'

    - name: chezmoi apply
      command: '{{ ansible_user_dir }}/bin/chezmoi apply'

    - name: purge config
      file:
        path: /etc/kubernetes
        state: absent
      become: yes

    - name: stop kubelet
      systemd:
        name: kubelet
        state: stopped
      become: yes

    - name: kubedm init
      command: kubeadm init --log-file={{ ansible_user_dir }}/kubeadm.log
      become: yes

    - name: kube config dir
      file:
        path: '{{ ansible_user_dir }}/.kube'
        state: directory

    - name: kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: '{{ ansible_user_dir }}/.kube/config'
        remote_src: true
      become: yes

    - name: calico config
      get_url:
        url: https://docs.projectcalico.org/manifests/calico.yaml
        dest: '{{ ansible_user_dir }}'

    - name: install calico
      command: kubectl apply -f calico.yaml

  handlers:
    - name: kubelet-restart
      systemd:
        name: kubelet
        state: restarted
        daemon_reload: true
      become: yes

    - name: docker-restart
      systemd:
        name: docker
        state: restarted
      become: yes
...
